// Generated by gencpp from file message/textResponse.msg
// DO NOT EDIT!


#ifndef MESSAGE_MESSAGE_TEXTRESPONSE_H
#define MESSAGE_MESSAGE_TEXTRESPONSE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace message
{
template <class ContainerAllocator>
struct textResponse_
{
  typedef textResponse_<ContainerAllocator> Type;

  textResponse_()
    : num(0)
    , result(0.0)  {
    }
  textResponse_(const ContainerAllocator& _alloc)
    : num(0)
    , result(0.0)  {
  (void)_alloc;
    }



   typedef int32_t _num_type;
  _num_type num;

   typedef float _result_type;
  _result_type result;





  typedef boost::shared_ptr< ::message::textResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::message::textResponse_<ContainerAllocator> const> ConstPtr;

}; // struct textResponse_

typedef ::message::textResponse_<std::allocator<void> > textResponse;

typedef boost::shared_ptr< ::message::textResponse > textResponsePtr;
typedef boost::shared_ptr< ::message::textResponse const> textResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::message::textResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::message::textResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::message::textResponse_<ContainerAllocator1> & lhs, const ::message::textResponse_<ContainerAllocator2> & rhs)
{
  return lhs.num == rhs.num &&
    lhs.result == rhs.result;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::message::textResponse_<ContainerAllocator1> & lhs, const ::message::textResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace message

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::message::textResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::message::textResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::message::textResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::message::textResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::message::textResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::message::textResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::message::textResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "9c63e8ce27cfeab537b464370e250d6a";
  }

  static const char* value(const ::message::textResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x9c63e8ce27cfeab5ULL;
  static const uint64_t static_value2 = 0x37b464370e250d6aULL;
};

template<class ContainerAllocator>
struct DataType< ::message::textResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "message/textResponse";
  }

  static const char* value(const ::message::textResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::message::textResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int32 num\n"
"float32 result\n"
;
  }

  static const char* value(const ::message::textResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::message::textResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.num);
      stream.next(m.result);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct textResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::message::textResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::message::textResponse_<ContainerAllocator>& v)
  {
    if (false || !indent.empty())
      s << std::endl;
    s << indent << "num: ";
    Printer<int32_t>::stream(s, indent + "  ", v.num);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "result: ";
    Printer<float>::stream(s, indent + "  ", v.result);
  }
};

} // namespace message_operations
} // namespace ros

#endif // MESSAGE_MESSAGE_TEXTRESPONSE_H
