// Generated by gencpp from file message/textRequest.msg
// DO NOT EDIT!


#ifndef MESSAGE_MESSAGE_TEXTREQUEST_H
#define MESSAGE_MESSAGE_TEXTREQUEST_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace message
{
template <class ContainerAllocator>
struct textRequest_
{
  typedef textRequest_<ContainerAllocator> Type;

  textRequest_()
    : num1(0)
    , num2(0)
    , age(0.0)  {
    }
  textRequest_(const ContainerAllocator& _alloc)
    : num1(0)
    , num2(0)
    , age(0.0)  {
  (void)_alloc;
    }



   typedef int32_t _num1_type;
  _num1_type num1;

   typedef int32_t _num2_type;
  _num2_type num2;

   typedef float _age_type;
  _age_type age;





  typedef boost::shared_ptr< ::message::textRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::message::textRequest_<ContainerAllocator> const> ConstPtr;

}; // struct textRequest_

typedef ::message::textRequest_<std::allocator<void> > textRequest;

typedef boost::shared_ptr< ::message::textRequest > textRequestPtr;
typedef boost::shared_ptr< ::message::textRequest const> textRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::message::textRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::message::textRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::message::textRequest_<ContainerAllocator1> & lhs, const ::message::textRequest_<ContainerAllocator2> & rhs)
{
  return lhs.num1 == rhs.num1 &&
    lhs.num2 == rhs.num2 &&
    lhs.age == rhs.age;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::message::textRequest_<ContainerAllocator1> & lhs, const ::message::textRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace message

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::message::textRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::message::textRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::message::textRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::message::textRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::message::textRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::message::textRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::message::textRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "5781eeaeeae3de8b661a7a379ce30fd2";
  }

  static const char* value(const ::message::textRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x5781eeaeeae3de8bULL;
  static const uint64_t static_value2 = 0x661a7a379ce30fd2ULL;
};

template<class ContainerAllocator>
struct DataType< ::message::textRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "message/textRequest";
  }

  static const char* value(const ::message::textRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::message::textRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int32 num1\n"
"int32 num2\n"
"float32 age\n"
;
  }

  static const char* value(const ::message::textRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::message::textRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.num1);
      stream.next(m.num2);
      stream.next(m.age);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct textRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::message::textRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::message::textRequest_<ContainerAllocator>& v)
  {
    if (false || !indent.empty())
      s << std::endl;
    s << indent << "num1: ";
    Printer<int32_t>::stream(s, indent + "  ", v.num1);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "num2: ";
    Printer<int32_t>::stream(s, indent + "  ", v.num2);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "age: ";
    Printer<float>::stream(s, indent + "  ", v.age);
  }
};

} // namespace message_operations
} // namespace ros

#endif // MESSAGE_MESSAGE_TEXTREQUEST_H
