// Generated by gencpp from file message/text.msg
// DO NOT EDIT!


#ifndef MESSAGE_MESSAGE_TEXT_H
#define MESSAGE_MESSAGE_TEXT_H

#include <ros/service_traits.h>


#include <message/textRequest.h>
#include <message/textResponse.h>


namespace message
{

struct text
{

typedef textRequest Request;
typedef textResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct text
} // namespace message


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::message::text > {
  static const char* value()
  {
    return "5c43c30d16420052e2be2adf23ac5da0";
  }

  static const char* value(const ::message::text&) { return value(); }
};

template<>
struct DataType< ::message::text > {
  static const char* value()
  {
    return "message/text";
  }

  static const char* value(const ::message::text&) { return value(); }
};


// service_traits::MD5Sum< ::message::textRequest> should match
// service_traits::MD5Sum< ::message::text >
template<>
struct MD5Sum< ::message::textRequest>
{
  static const char* value()
  {
    return MD5Sum< ::message::text >::value();
  }
  static const char* value(const ::message::textRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::message::textRequest> should match
// service_traits::DataType< ::message::text >
template<>
struct DataType< ::message::textRequest>
{
  static const char* value()
  {
    return DataType< ::message::text >::value();
  }
  static const char* value(const ::message::textRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::message::textResponse> should match
// service_traits::MD5Sum< ::message::text >
template<>
struct MD5Sum< ::message::textResponse>
{
  static const char* value()
  {
    return MD5Sum< ::message::text >::value();
  }
  static const char* value(const ::message::textResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::message::textResponse> should match
// service_traits::DataType< ::message::text >
template<>
struct DataType< ::message::textResponse>
{
  static const char* value()
  {
    return DataType< ::message::text >::value();
  }
  static const char* value(const ::message::textResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // MESSAGE_MESSAGE_TEXT_H
